---
- name: "EXABGP - Get interfaces"
  shell: ifconfig -a
  register: network_interfaces

- name: "EXABGP - print"
  debug:
    msg: "{{ network_interfaces.stdout_lines }}"

- name: "EXABGP - Confirm interfaces"
  pause:
    prompt: "Please check if network interfaces above are correct.\n\nPress any key to continue[Ctrl+C and then 'A' for abort]"
  when: force == false

- name: "EXABGP - Ensure that directory are created"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop: "{{ exabgp_dirs }}"

- name: "EXABGP - Copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ exabgp_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ exabgp_files }}"
  notify: "docker exabgp restart"

- name: "EXABGP - Create files from template"
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ exabgp_path }}/{{ item.dest | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ exabgp_templates }}"
  notify: "docker exabgp restart"

- name: "EXABGP - Create docker-compose.yml from template"
  template:
    src: "{{ exabgp_docker_compose_template }}.j2"
    dest: "{{ exabgp_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - upgrade_docker_containers
    - exabgp_upgrade_docker_container
  notify: "docker exabgp restart"

- name: "EXABGP - Ensure that docker image is started"
  command: /bin/true
  notify: "docker exabgp start"
  when: exabgp_force_start == True
  tags:
    - upgrade_docker_containers
    - exabgp_upgrade_docker_container
